/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_Filters_Local_PixelwiseFilter */

#ifndef _Included_Beatmup_Imaging_Filters_Local_PixelwiseFilter
#define _Included_Beatmup_Imaging_Filters_Local_PixelwiseFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Imaging_Filters_Local_PixelwiseFilter
 * Method:    setBitmaps
 * Signature: (JLBeatmup/Bitmap;LBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_Local_PixelwiseFilter_setBitmaps
  (JNIEnv *, jobject, jlong, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
