/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Bitmap */

#ifndef _Included_Beatmup_Bitmap
#define _Included_Beatmup_Bitmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Bitmap
 * Method:    newInternalBitmap
 * Signature: (LBeatmup/Context;III)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Bitmap_newInternalBitmap
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     Beatmup_Bitmap
 * Method:    newNativeBitmap
 * Signature: (LBeatmup/Context;Landroid/graphics/Bitmap;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Bitmap_newNativeBitmap
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     Beatmup_Bitmap
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Bitmap_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Bitmap
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Bitmap_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Bitmap
 * Method:    getPixelFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Bitmap_getPixelFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Bitmap
 * Method:    zero
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Bitmap_zero
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Bitmap
 * Method:    crop
 * Signature: (JJIIIIII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Bitmap_crop
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Beatmup_Bitmap
 * Method:    pullPixels
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Bitmap_pullPixels
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
