/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_Filters_Local_Sepia */

#ifndef _Included_Beatmup_Imaging_Filters_Local_Sepia
#define _Included_Beatmup_Imaging_Filters_Local_Sepia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Imaging_Filters_Local_Sepia
 * Method:    newSepia
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Imaging_Filters_Local_Sepia_newSepia
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
