/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_FloodFill_BorderMorphology */

#ifndef _Included_Beatmup_Imaging_FloodFill_BorderMorphology
#define _Included_Beatmup_Imaging_FloodFill_BorderMorphology
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
