/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Rendering_Scene */

#ifndef _Included_Beatmup_Rendering_Scene
#define _Included_Beatmup_Rendering_Scene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    newScene
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Rendering_Scene_newScene
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    newSceneLayer
 * Signature: (JLBeatmup/Rendering/Scene/SceneLayer;LBeatmup/Rendering/Scene;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Rendering_Scene_newSceneLayer
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    newBitmapLayer
 * Signature: (JLBeatmup/Rendering/Scene/BitmapLayer;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Rendering_Scene_newBitmapLayer
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    newMaskedBitmapLayer
 * Signature: (JLBeatmup/Rendering/Scene/MaskedBitmapLayer;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Rendering_Scene_newMaskedBitmapLayer
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    newShapedBitmapLayer
 * Signature: (JLBeatmup/Rendering/Scene/ShapedBitmapLayer;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Rendering_Scene_newShapedBitmapLayer
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    newShadedBitmapLayer
 * Signature: (JLBeatmup/Rendering/Scene/ShadedBitmapLayer;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Rendering_Scene_newShadedBitmapLayer
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    deleteLayers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_deleteLayers
  (JNIEnv *, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Rendering_Scene_getLayerCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerByIndex
 * Signature: (JI)LBeatmup/Rendering/Scene/Layer;
 */
JNIEXPORT jobject JNICALL Java_Beatmup_Rendering_Scene_getLayerByIndex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerByName
 * Signature: (JLjava/lang/String;)LBeatmup/Rendering/Scene/Layer;
 */
JNIEXPORT jobject JNICALL Java_Beatmup_Rendering_Scene_getLayerByName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerAtPoint
 * Signature: (JFF)LBeatmup/Rendering/Scene/Layer;
 */
JNIEXPORT jobject JNICALL Java_Beatmup_Rendering_Scene_getLayerAtPoint
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setLayerName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setLayerName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Beatmup_Rendering_Scene_getLayerName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setLayerVisibility
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setLayerVisibility
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerVisibility
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_Beatmup_Rendering_Scene_getLayerVisibility
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setLayerPhantomFlag
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setLayerPhantomFlag
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerPhantomFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_Beatmup_Rendering_Scene_getLayerPhantomFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setLayerTransform
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setLayerTransform
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerTransform
 * Signature: (JLBeatmup/Geometry/AffineMapping;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_getLayerTransform
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setLayerX
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setLayerX
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getLayerX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setLayerY
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setLayerY
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getLayerY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerScaleX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getLayerScaleX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerScaleY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getLayerScaleY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getLayerOrientation
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getLayerOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setLayerCenterPos
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setLayerCenterPos
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    scaleLayer
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_scaleLayer
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    rotateLayer
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_rotateLayer
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setBitmapLayerImageSource
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setBitmapLayerImageSource
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getBitmapLayerImageSource
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Rendering_Scene_getBitmapLayerImageSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setBitmapLayerModulationColor
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setBitmapLayerModulationColor
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getBitmapLayerModulationColor
 * Signature: (JLBeatmup/Imaging/Color;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_getBitmapLayerModulationColor
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setBitmapLayerMaskPos
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setBitmapLayerMaskPos
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    scaleBitmapLayerMask
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_scaleBitmapLayerMask
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    rotateBitmapLayerMask
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_rotateBitmapLayerMask
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    skewBitmapLayerMask
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_skewBitmapLayerMask
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setBitmapLayerBgColor
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setBitmapLayerBgColor
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getBitmapLayerBgColor
 * Signature: (JLBeatmup/Imaging/Color;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_getBitmapLayerBgColor
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setBitmapLayerImageTransform
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setBitmapLayerImageTransform
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getBitmapLayerImageTransform
 * Signature: (JLBeatmup/Geometry/AffineMapping;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_getBitmapLayerImageTransform
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setBitmapLayerMaskTransform
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setBitmapLayerMaskTransform
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getBitmapLayerMaskTransform
 * Signature: (JLBeatmup/Geometry/AffineMapping;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_getBitmapLayerMaskTransform
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setBitmapLayerBitmap
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setBitmapLayerBitmap
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setMaskedBitmapLayerMask
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setMaskedBitmapLayerMask
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setShapedBitmapLayerInPixelsSwitch
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setShapedBitmapLayerInPixelsSwitch
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getShapedBitmapLayerInPixelsSwitch
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_Beatmup_Rendering_Scene_getShapedBitmapLayerInPixelsSwitch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setShapedBitmapLayerCornerRadius
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setShapedBitmapLayerCornerRadius
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getShapedBitmapLayerCornerRadius
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getShapedBitmapLayerCornerRadius
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setShapedBitmapLayerBorderWidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setShapedBitmapLayerBorderWidth
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getShapedBitmapLayerBorderWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getShapedBitmapLayerBorderWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setShapedBitmapLayerSlopeWidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setShapedBitmapLayerSlopeWidth
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    getShapedBitmapLayerSlopeWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Rendering_Scene_getShapedBitmapLayerSlopeWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Rendering_Scene
 * Method:    setShadedBitmapLayerShader
 * Signature: (JLBeatmup/Shading/Shader;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Rendering_Scene_setShadedBitmapLayerShader
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
