/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Audio_Source_Harmonic */

#ifndef _Included_Beatmup_Audio_Source_Harmonic
#define _Included_Beatmup_Audio_Source_Harmonic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Audio_Source_Harmonic
 * Method:    newHarmonicSource
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Audio_Source_Harmonic_newHarmonicSource
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Audio_Source_Harmonic
 * Method:    setFrequency
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_Source_Harmonic_setFrequency
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Audio_Source_Harmonic
 * Method:    setPhase
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_Source_Harmonic_setPhase
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Audio_Source_Harmonic
 * Method:    setAmplitude
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_Source_Harmonic_setAmplitude
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
