/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Audio_Playback */

#ifndef _Included_Beatmup_Audio_Playback
#define _Included_Beatmup_Audio_Playback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Audio_Playback
 * Method:    newPlayback
 * Signature: (LBeatmup/Context;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Audio_Playback_newPlayback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Beatmup_Audio_Playback
 * Method:    configure
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_Playback_configure
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     Beatmup_Audio_Playback
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_Playback_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Audio_Playback
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_Playback_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Audio_Playback
 * Method:    setSource
 * Signature: (JLBeatmup/Audio/Source/AbstractSource;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_Playback_setSource
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
