/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Audio_SignalPlot */

#ifndef _Included_Beatmup_Audio_SignalPlot
#define _Included_Beatmup_Audio_SignalPlot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    newSignalPlot
 * Signature: (LBeatmup/Context;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Audio_SignalPlot_newSignalPlot
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    prepareMetering
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_SignalPlot_prepareMetering
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    setSignal
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_SignalPlot_setSignal
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    setBitmap
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_SignalPlot_setBitmap
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    setWindow
 * Signature: (JIIIIF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_SignalPlot_setWindow
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jfloat);

/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    setPlotArea
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_SignalPlot_setPlotArea
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    setPalette
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_SignalPlot_setPalette
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     Beatmup_Audio_SignalPlot
 * Method:    setChannels
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Audio_SignalPlot_setChannels
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
