/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Shading_Shader */

#ifndef _Included_Beatmup_Shading_Shader
#define _Included_Beatmup_Shading_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Shading_Shader
 * Method:    newShader
 * Signature: (LBeatmup/Context;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Shading_Shader_newShader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Beatmup_Shading_Shader
 * Method:    setSourceCode
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Shading_Shader_setSourceCode
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
