/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Android_Context */

#ifndef _Included_Beatmup_Android_Context
#define _Included_Beatmup_Android_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Android_Context
 * Method:    newEnvironment
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Android_Context_newEnvironment
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     Beatmup_Android_Context
 * Method:    initCamTexture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Beatmup_Android_Context_initCamTexture
  (JNIEnv *, jobject);

/*
 * Class:     Beatmup_Android_Context
 * Method:    cameraTextureUpdated
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Android_Context_cameraTextureUpdated
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
