/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_Filters_Resampler */

#ifndef _Included_Beatmup_Imaging_Filters_Resampler
#define _Included_Beatmup_Imaging_Filters_Resampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Imaging_Filters_Resampler
 * Method:    newResampler
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Imaging_Filters_Resampler_newResampler
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Imaging_Filters_Resampler
 * Method:    setBitmaps
 * Signature: (JLBeatmup/Bitmap;LBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_Resampler_setBitmaps
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     Beatmup_Imaging_Filters_Resampler
 * Method:    setMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_Resampler_setMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Beatmup_Imaging_Filters_Resampler
 * Method:    getMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Imaging_Filters_Resampler_getMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Imaging_Filters_Resampler
 * Method:    setCubicParameter
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_Resampler_setCubicParameter
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Imaging_Filters_Resampler
 * Method:    getCubicParameter
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Imaging_Filters_Resampler_getCubicParameter
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
