/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Pipelining_Multitask */

#ifndef _Included_Beatmup_Pipelining_Multitask
#define _Included_Beatmup_Pipelining_Multitask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Pipelining_Multitask
 * Method:    newMultitask
 * Signature: (LBeatmup/Context;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Pipelining_Multitask_newMultitask
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Beatmup_Pipelining_Multitask
 * Method:    getRepetitionPolicy
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Pipelining_Multitask_getRepetitionPolicy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Beatmup_Pipelining_Multitask
 * Method:    setRepetitionPolicy
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Pipelining_Multitask_setRepetitionPolicy
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
