/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_Filters_Resampler_Mode */

#ifndef _Included_Beatmup_Imaging_Filters_Resampler_Mode
#define _Included_Beatmup_Imaging_Filters_Resampler_Mode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
