/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Android_Context */

#ifndef _Included_Beatmup_Android_Context
#define _Included_Beatmup_Android_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Android_Context
 * Method:    newEnvironment
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Android_Context_newEnvironment
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
