/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_Filters_ImageTuning */

#ifndef _Included_Beatmup_Imaging_Filters_ImageTuning
#define _Included_Beatmup_Imaging_Filters_ImageTuning
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    newImageTuning
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_newImageTuning
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    setBitmaps
 * Signature: (JLBeatmup/Bitmap;LBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_setBitmaps
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    setHueOffset
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_setHueOffset
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    setSaturationFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_setSaturationFactor
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    setValueFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_setValueFactor
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    setBrightness
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_setBrightness
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    setContrast
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_setContrast
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    getHueOffset
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_getHueOffset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    getSaturationFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_getSaturationFactor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    getValueFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_getValueFactor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    getBrightness
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_getBrightness
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Imaging_Filters_ImageTuning
 * Method:    getContrast
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Imaging_Filters_ImageTuning_getContrast
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
