/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Object */

#ifndef _Included_Beatmup_Object
#define _Included_Beatmup_Object
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Object
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Beatmup_Object_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
