/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Visual_Android_BasicDisplay_OnBindingListener */

#ifndef _Included_Beatmup_Visual_Android_BasicDisplay_OnBindingListener
#define _Included_Beatmup_Visual_Android_BasicDisplay_OnBindingListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
