/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Utils_ChunkFile */

#ifndef _Included_Beatmup_Utils_ChunkFile
#define _Included_Beatmup_Utils_ChunkFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Utils_ChunkFile
 * Method:    newChunkfile
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Utils_ChunkFile_newChunkfile
  (JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
