/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_NNets_InferenceTask */

#ifndef _Included_Beatmup_NNets_InferenceTask
#define _Included_Beatmup_NNets_InferenceTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_NNets_InferenceTask
 * Method:    newInferenceTask
 * Signature: (LBeatmup/NNets/Model;LBeatmup/Utils/ChunkCollection;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_NNets_InferenceTask_newInferenceTask
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     Beatmup_NNets_InferenceTask
 * Method:    connectByName
 * Signature: (JLBeatmup/Bitmap;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Beatmup_NNets_InferenceTask_connectByName
  (JNIEnv *, jobject, jlong, jobject, jstring, jint);

/*
 * Class:     Beatmup_NNets_InferenceTask
 * Method:    connectByHandle
 * Signature: (JLBeatmup/Bitmap;JI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_NNets_InferenceTask_connectByHandle
  (JNIEnv *, jobject, jlong, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
