/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_BinaryOperation_Operation */

#ifndef _Included_Beatmup_Imaging_BinaryOperation_Operation
#define _Included_Beatmup_Imaging_BinaryOperation_Operation
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
