/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_Filters_ColorMatrixTransform_Preset */

#ifndef _Included_Beatmup_Imaging_Filters_ColorMatrixTransform_Preset
#define _Included_Beatmup_Imaging_Filters_ColorMatrixTransform_Preset
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
