/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Pipelining_TaskHolder */

#ifndef _Included_Beatmup_Pipelining_TaskHolder
#define _Included_Beatmup_Pipelining_TaskHolder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Pipelining_TaskHolder
 * Method:    getRunTime
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_Beatmup_Pipelining_TaskHolder_getRunTime
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
