/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Rendering_Scene_BitmapLayer_ImageSource */

#ifndef _Included_Beatmup_Rendering_Scene_BitmapLayer_ImageSource
#define _Included_Beatmup_Rendering_Scene_BitmapLayer_ImageSource
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
