/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_NNets_DeserializedModel */

#ifndef _Included_Beatmup_NNets_DeserializedModel
#define _Included_Beatmup_NNets_DeserializedModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_NNets_DeserializedModel
 * Method:    newDeserializedModel
 * Signature: (LBeatmup/Context;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_NNets_DeserializedModel_newDeserializedModel
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
