/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Rendering_Scene_ShapedBitmapLayer */

#ifndef _Included_Beatmup_Rendering_Scene_ShapedBitmapLayer
#define _Included_Beatmup_Rendering_Scene_ShapedBitmapLayer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
