/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Audio_Signal_Source */

#ifndef _Included_Beatmup_Audio_Signal_Source
#define _Included_Beatmup_Audio_Signal_Source
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
