/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Bitmap_BadPixelFormat */

#ifndef _Included_Beatmup_Bitmap_BadPixelFormat
#define _Included_Beatmup_Bitmap_BadPixelFormat
#ifdef __cplusplus
extern "C" {
#endif
#undef Beatmup_Bitmap_BadPixelFormat_serialVersionUID
#define Beatmup_Bitmap_BadPixelFormat_serialVersionUID -3042686055658047285LL
#undef Beatmup_Bitmap_BadPixelFormat_serialVersionUID
#define Beatmup_Bitmap_BadPixelFormat_serialVersionUID -3387516993124229948LL
#undef Beatmup_Bitmap_BadPixelFormat_serialVersionUID
#define Beatmup_Bitmap_BadPixelFormat_serialVersionUID -7034897190745766939LL
#undef Beatmup_Bitmap_BadPixelFormat_serialVersionUID
#define Beatmup_Bitmap_BadPixelFormat_serialVersionUID -5365630128856068164LL
#ifdef __cplusplus
}
#endif
#endif
