/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Shading_ImageShader */

#ifndef _Included_Beatmup_Shading_ImageShader
#define _Included_Beatmup_Shading_ImageShader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Shading_ImageShader
 * Method:    newImageShader
 * Signature: (LBeatmup/Context;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Shading_ImageShader_newImageShader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Beatmup_Shading_ImageShader
 * Method:    setSourceCode
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Shading_ImageShader_setSourceCode
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     Beatmup_Shading_ImageShader
 * Method:    getInputImageId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Beatmup_Shading_ImageShader_getInputImageId
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Shading_ImageShader
 * Method:    getInputImageDeclType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Beatmup_Shading_ImageShader_getInputImageDeclType
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
