/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_NNets_ImageSampler */

#ifndef _Included_Beatmup_NNets_ImageSampler
#define _Included_Beatmup_NNets_ImageSampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_NNets_ImageSampler
 * Method:    setRotation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_NNets_ImageSampler_setRotation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     Beatmup_NNets_ImageSampler
 * Method:    getRotation
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_NNets_ImageSampler_getRotation
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
