/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_Filters_PixelwiseFilter */

#ifndef _Included_Beatmup_Imaging_Filters_PixelwiseFilter
#define _Included_Beatmup_Imaging_Filters_PixelwiseFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Imaging_Filters_PixelwiseFilter
 * Method:    setInput
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_PixelwiseFilter_setInput
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Imaging_Filters_PixelwiseFilter
 * Method:    setOutput
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_Filters_PixelwiseFilter_setOutput
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
