/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Utils_ChunkAsset */

#ifndef _Included_Beatmup_Utils_ChunkAsset
#define _Included_Beatmup_Utils_ChunkAsset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Utils_ChunkAsset
 * Method:    newChunkAsset
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Utils_ChunkAsset_newChunkAsset
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
