/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Rendering_Scene_MaskedBitmapLayer */

#ifndef _Included_Beatmup_Rendering_Scene_MaskedBitmapLayer
#define _Included_Beatmup_Rendering_Scene_MaskedBitmapLayer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
