/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_FloodFill */

#ifndef _Included_Beatmup_Imaging_FloodFill
#define _Included_Beatmup_Imaging_FloodFill
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    newFloodFill
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Imaging_FloodFill_newFloodFill
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    setInput
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_FloodFill_setInput
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    setOutput
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_FloodFill_setOutput
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    setMaskPos
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_FloodFill_setMaskPos
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    setTolerance
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_FloodFill_setTolerance
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    setBorderPostprocessing
 * Signature: (JIFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_FloodFill_setBorderPostprocessing
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    setSeeds
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_FloodFill_setSeeds
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    setComputeContours
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_FloodFill_setComputeContours
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    getContourCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Imaging_FloodFill_getContourCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    getContourPointCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Imaging_FloodFill_getContourPointCount
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    getContour
 * Signature: (JIF)[I
 */
JNIEXPORT jintArray JNICALL Java_Beatmup_Imaging_FloodFill_getContour
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     Beatmup_Imaging_FloodFill
 * Method:    getBoundingBox
 * Signature: (J)LBeatmup/Geometry/IntRectangle;
 */
JNIEXPORT jobject JNICALL Java_Beatmup_Imaging_FloodFill_getBoundingBox
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
