/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_NNets_Softmax */

#ifndef _Included_Beatmup_NNets_Softmax
#define _Included_Beatmup_NNets_Softmax
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_NNets_Softmax
 * Method:    getProbabilities
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_Beatmup_NNets_Softmax_getProbabilities
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
