/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Rendering_SceneRenderer_OutputMapping */

#ifndef _Included_Beatmup_Rendering_SceneRenderer_OutputMapping
#define _Included_Beatmup_Rendering_SceneRenderer_OutputMapping
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
