/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Pipelining_CustomPipeline */

#ifndef _Included_Beatmup_Pipelining_CustomPipeline
#define _Included_Beatmup_Pipelining_CustomPipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Pipelining_CustomPipeline
 * Method:    getTaskCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Pipelining_CustomPipeline_getTaskCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Pipelining_CustomPipeline
 * Method:    getTask
 * Signature: (JI)LBeatmup/Pipelining/TaskHolder;
 */
JNIEXPORT jobject JNICALL Java_Beatmup_Pipelining_CustomPipeline_getTask
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Beatmup_Pipelining_CustomPipeline
 * Method:    getTaskIndex
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_Beatmup_Pipelining_CustomPipeline_getTaskIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Beatmup_Pipelining_CustomPipeline
 * Method:    addTask
 * Signature: (JLBeatmup/Pipelining/TaskHolder;LBeatmup/Task;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Pipelining_CustomPipeline_addTask
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     Beatmup_Pipelining_CustomPipeline
 * Method:    insertTask
 * Signature: (JLBeatmup/Pipelining/TaskHolder;LBeatmup/Task;J)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Pipelining_CustomPipeline_insertTask
  (JNIEnv *, jobject, jlong, jobject, jobject, jlong);

/*
 * Class:     Beatmup_Pipelining_CustomPipeline
 * Method:    removeTask
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_Beatmup_Pipelining_CustomPipeline_removeTask
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Beatmup_Pipelining_CustomPipeline
 * Method:    measure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Pipelining_CustomPipeline_measure
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
