/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_NNets_AbstractOperation */

#ifndef _Included_Beatmup_NNets_AbstractOperation
#define _Included_Beatmup_NNets_AbstractOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_NNets_AbstractOperation
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Beatmup_NNets_AbstractOperation_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_NNets_AbstractOperation
 * Method:    countMultiplyAdds
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_NNets_AbstractOperation_countMultiplyAdds
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_NNets_AbstractOperation
 * Method:    getOperationFromModel
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_NNets_AbstractOperation_getOperationFromModel
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
