/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Imaging_BinaryOperation */

#ifndef _Included_Beatmup_Imaging_BinaryOperation
#define _Included_Beatmup_Imaging_BinaryOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    newBinaryOperation
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Imaging_BinaryOperation_newBinaryOperation
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    setOperand1
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_BinaryOperation_setOperand1
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    setOperand2
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_BinaryOperation_setOperand2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    setOutput
 * Signature: (JLBeatmup/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_BinaryOperation_setOutput
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    setOperation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_BinaryOperation_setOperation
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    resetCrop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_BinaryOperation_resetCrop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    setCrop
 * Signature: (JIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_BinaryOperation_setCrop
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Beatmup_Imaging_BinaryOperation
 * Method:    getCrop
 * Signature: (JLBeatmup/Geometry/IntPoint;LBeatmup/Geometry/IntPoint;LBeatmup/Geometry/IntPoint;LBeatmup/Geometry/IntPoint;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Imaging_BinaryOperation_getCrop
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
