/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Utils_VariablesBundle */

#ifndef _Included_Beatmup_Utils_VariablesBundle
#define _Included_Beatmup_Utils_VariablesBundle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setInteger1
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setInteger1
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setInteger2
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setInteger2
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setInteger3
 * Signature: (JLjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setInteger3
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setInteger4
 * Signature: (JLjava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setInteger4
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint, jint);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setFloat1
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setFloat1
  (JNIEnv *, jobject, jlong, jstring, jfloat);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setFloat2
 * Signature: (JLjava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setFloat2
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setFloat3
 * Signature: (JLjava/lang/String;FFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setFloat3
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setFloat4
 * Signature: (JLjava/lang/String;FFFF)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setFloat4
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setFloatMatrix
 * Signature: (JLjava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setFloatMatrix
  (JNIEnv *, jobject, jlong, jstring, jfloatArray);

/*
 * Class:     Beatmup_Utils_VariablesBundle
 * Method:    setFloatMatrixFromColorMatrix
 * Signature: (JLjava/lang/String;LBeatmup/Imaging/ColorMatrix;)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_VariablesBundle_setFloatMatrixFromColorMatrix
  (JNIEnv *, jobject, jlong, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
