/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Sequence */

#ifndef _Included_Beatmup_Sequence
#define _Included_Beatmup_Sequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Sequence
 * Method:    copy
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Sequence_copy
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     Beatmup_Sequence
 * Method:    insert
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Sequence_insert
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     Beatmup_Sequence
 * Method:    remove
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Sequence_remove
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     Beatmup_Sequence
 * Method:    shrink
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Sequence_shrink
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
