/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Pipelining_Multitask_RepetitionPolicy */

#ifndef _Included_Beatmup_Pipelining_Multitask_RepetitionPolicy
#define _Included_Beatmup_Pipelining_Multitask_RepetitionPolicy
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
