/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Utils_Callback */

#ifndef _Included_Beatmup_Utils_Callback
#define _Included_Beatmup_Utils_Callback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Utils_Callback
 * Method:    newCallbackTask
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Utils_Callback_newCallbackTask
  (JNIEnv *, jclass);

/*
 * Class:     Beatmup_Utils_Callback
 * Method:    updateCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_Callback_updateCallback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
