/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Android_ExternalBitmap */

#ifndef _Included_Beatmup_Android_ExternalBitmap
#define _Included_Beatmup_Android_ExternalBitmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Android_ExternalBitmap
 * Method:    newExternalImage
 * Signature: (LBeatmup/Context;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Android_ExternalBitmap_newExternalImage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Beatmup_Android_ExternalBitmap
 * Method:    bind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Android_ExternalBitmap_bind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Android_ExternalBitmap
 * Method:    notifyUpdate
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Android_ExternalBitmap_notifyUpdate
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
