/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Utils_ChunkCollection */

#ifndef _Included_Beatmup_Utils_ChunkCollection
#define _Included_Beatmup_Utils_ChunkCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Utils_ChunkCollection
 * Method:    open
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_ChunkCollection_open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Utils_ChunkCollection
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_ChunkCollection_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Utils_ChunkCollection
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Utils_ChunkCollection_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_Utils_ChunkCollection
 * Method:    chunkExists
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Beatmup_Utils_ChunkCollection_chunkExists
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     Beatmup_Utils_ChunkCollection
 * Method:    chunkSize
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Utils_ChunkCollection_chunkSize
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     Beatmup_Utils_ChunkCollection
 * Method:    save
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_Beatmup_Utils_ChunkCollection_save
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     Beatmup_Utils_ChunkCollection
 * Method:    read
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Beatmup_Utils_ChunkCollection_read
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
