/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_NNets_Model */

#ifndef _Included_Beatmup_NNets_Model
#define _Included_Beatmup_NNets_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_NNets_Model
 * Method:    serializeToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Beatmup_NNets_Model_serializeToString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_NNets_Model
 * Method:    countMultiplyAdds
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_NNets_Model_countMultiplyAdds
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_NNets_Model
 * Method:    getMemorySize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_NNets_Model_getMemorySize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Beatmup_NNets_Model
 * Method:    getNumberOfOperations
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_NNets_Model_getNumberOfOperations
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
