/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Beatmup_Android_Context */

#ifndef _Included_Beatmup_Android_Context
#define _Included_Beatmup_Android_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Beatmup_Android_Context
 * Method:    newContext
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_Beatmup_Android_Context_newContext
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
