name: android

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: master
  schedule:
    - cron: '5 9 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: beatmup
          ref: ${{ github.ref }}
          submodules: false

      - name: Prepare docker action
        run: mv ./beatmup/dockerfiles/android.Dockerfile ./beatmup/Dockerfile

      - name: Build android app
        uses: ./beatmup
